midtermBioData/urls.py
from django.urls import include, path
from . import views
from . import api 

# I wrote this code with guidance of lecture videos 
urlpatterns = [
    # main view urls
    path('', views.index, name='index'),
    path('proteins/', views.proteins, name='proteins'),
    path('protein/<str:protein_id>', views.protein, name='protein'),

    # api urls  
    path('api/protein/<str:protein_id>', api.protein_detail, name='protein_detail'),
    path('api/pfam/<str:pfam_id>', api.get_domain, name='get_domain'),
    path('api/proteins/<int:taxa_id>', api.get_organism_proteins, name='get_proteins'),
    path('api/pfams/<int:taxa_id>', api.get_pfams, name='get_pfams'),
    path('api/coverage/<str:protein_id>', api.get_coverage, name='get_coverage'), 
]
# End of code I wrote this code with guidance of lecture videos 

midtermProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('midtermBioData.urls')),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

midtermBioData/models.py
from django.db import models

# I wrote this code 
class Organism(models.Model):
    taxa_id = models.IntegerField(primary_key=True) 
    genus = models.CharField(max_length=100)
    species = models.CharField(max_length=100)

    def __str__(self):
        return str(self.taxa_id)

class Protein(models.Model):
    custom_pk = models.AutoField(primary_key=True)
    protein_id = models.CharField(max_length=100)
    clade = models.CharField(max_length=100)
    length = models.IntegerField()
    pfam_id = models.CharField(max_length=100)
    taxa_id = models.ForeignKey(Organism, on_delete=models.CASCADE)

    def __str__(self):
        return self.protein_id
    
class Domain(models.Model):
    pfam_id = models.CharField(max_length=100)
    protein_id = models.ManyToManyField(Protein, related_name='domains')
    description = models.CharField(max_length=100)
    start = models.IntegerField()
    stop = models.IntegerField()

    def __str__(self):
        return self.pfam_id
    
class PfamID(models.Model):
    domain_id = models.OneToOneField(Domain, on_delete=models.CASCADE, primary_key=True)
    domain_description = models.CharField(max_length=100)

    def __str__(self):
        return self.domain_description
        
class Sequence(models.Model):
    id = models.AutoField(primary_key=True, default=None)
    protein_id = models.ForeignKey(Protein, on_delete=models.CASCADE, related_name='sequences', null=True, default=None)
    sequence = models.CharField(max_length=600)

    def __str__(self):
        return f"Sequence for {self.protein_id}"
    


# End of code I wrote 

midtermBioData/forms.py
from django import forms 
from .models import *

# I wrote this code guided by lecture material
class ProteinForm(forms.ModelForm): 
     class Meta:
        model = Protein
        fields = ['protein_id', 'clade', 'length', 'pfam_id', 'taxa_id']
# End of code I wrote this code guided by lecture material
 

midtermBioData/views.py
from django.shortcuts import render
from .models import *
from .forms import ProteinForm
from django.http import HttpResponseRedirect
from django.contrib import messages

# I wrote this code guided by lecture material 
# home page view - renders index.html passing all proteins in as context data
def index(request): 
    proteins = Protein.objects.all()
    return render(request, 'midtermBioData/index.html', {'proteins':proteins})
# End of code I wrote guided by lecture material 

# proteins page view - renders proteins.html passing in all proteins currently in database 
# and protein form for posting data
def proteins(request):

# I wrote this code guided structurally by lecture material
    proteins = Protein.objects.all()
    if request.method == 'POST': 
        # initilaize protein form 
        form = ProteinForm(request.POST)
        # If form data is validly entered, get cleaned data 
        if form.is_valid():
            # initialize protein object for database
            protein = Protein()
            # get all fields from form
            protein.protein_id = form.cleaned_data['protein_id']
            protein.clade = form.cleaned_data['clade']
            protein.length = form.cleaned_data['length']
            protein.pfam_id = form.cleaned_data['pfam_id']
            protein.taxa_id = form.cleaned_data['taxa_id']
            # save protein object to database 
            protein.save() 
            messages.success(request, 'Protein added successfully.')
            return HttpResponseRedirect('/proteins/')
    # else if method is not post, display form
    else:
        form = ProteinForm() 
        return render(request, 'midtermBioData/proteins.html', {'proteins':proteins, 'form':form})
# End of code I wrote guided structurally by lecture material


# protein page view - renders protein.html - displays details of protein that has been clicked on
def protein(request, protein_id):
    # try retrieving all protein data based on protein clicked on from proteins page 
    try: 
        # I wrote all queries but required online help from documentation with bugs
        proteins = Protein.objects.filter(protein_id=protein_id)
        sequence = Sequence.objects.get(protein_id__in=proteins)   
        organism = Organism.objects.get(taxa_id=proteins.first().taxa_id.taxa_id)
        domains = Domain.objects.filter(protein_id__in=proteins).distinct()
        pfam_ids = PfamID.objects.filter(domain_id__pfam_id__in=domains.values('pfam_id'))

        first_protein = proteins.first()
        # End of queries code I wrote requiring online help from documentation with bugs
    
    # except if protein does not exist 
    except Protein.DoesNotExist:
        pass
    # render protein page with context data for displaying proteins
    return render(request, 'midtermBioData/protein.html', {'pfam_ids': pfam_ids, 'first_protein': first_protein,'organism': organism, 'proteins':proteins,  'sequence': sequence, 'domains': domains})
   
    
   

midtermBioData/templates/midtermBioData/base.html
<!-- This code is written guided by lecture content -->
{%load bootstrap4 %}
{% load static %}
{% include "./header.html" %}
{% include "./title.html" %}

<div class="content">
    {% block content %} Did not render content {% endblock %}
</div>

{% include "./footer.html" %}
<!-- End of code written guided by lecture content -->

midtermBioData/templates/midtermBioData/footer.html
<!-- This code is written guided by lecture content -->
{% load bootstrap4 %}
{% load date %}

<div id="footer"> 
    <hr>
    <p> Author: R. Fetsch -- {% todays_date %} </p>
</div>
</body>
</html>
<!-- End of code written guided by lecture content -->

midtermBioData/templates/midtermBioData/header.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
<!-- This code comes from lecture material -->
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
        <link rel="stylesheet" type="text/css"  href="{% static '/css/biodata.css' %}">
<!-- End of code from lecture material -->
        <style> 
        /* I wrote this code */
        .container {
            display: flex;
            justify-content: flex-start;
        }
        .proteins-list {
            flex: 1;
            border-right: 1px solid #ccc;
            padding-right: 20px;  
        }
        .form-container {
            flex: 7;
            padding-left: 20px;
        }
        /* end of code I wrote  */
        </style>
    </head>
    <body>
       

midtermBioData/templates/midtermBioData/index.html
{% extends "./base.html" %}
{% load bootstrap4 %}

<!-- I wrote this code -->
{% block content %}
    <h3> API Endpoints: </h3>
    <div id="endpoints"> 
        <p> <b> <em> GET  http://127.0.0.1:8000/api/protein/[PROTEIN ID] </b> </em>- return the protein sequence and all we know about it </p>
        <p> e.g. <a href="api/protein/A0A016S8J7"> http://127.0.0.1:8000/api/protein/A0A016S8J7 </a> </p>
        
        <p> <b> <em> GET  http://127.0.0.1:8000/api/pfam/[PFAM ID]  </b> </em>- return the domain and it's description </p>
        <p> e.g. <a href="api/pfam/PF00360 ">http://127.0.0.1:8000/api/pfam/PF00360  </a> </p>

        <p> <b> <em> GET  http://127.0.0.1:8000/api/proteins/[TAXA ID]  </b> </em>- return a list of all proteins for a given organism </p>
        <p> e.g. <a href="api/proteins/55661 ">http://127.0.0.1:8000/api/proteins/55661  </a> </p>
        
        <p> <b> <em> GET  http://127.0.0.1:8000/api/pfams/[TAXA ID]  </b> </em>-  return a list of all domains in all the proteins for a given organism</p>
        <p> e.g. <a href="api/pfams/55661 ">http://127.0.0.1:8000/api/pfams/55661   </a> </p>
        
        <p> <b> <em>GET  http://127.0.0.1:8000/api/coverage/[PROTEIN ID]   </b> </em>-  return a list of all domains in all the proteins for a given organism</p>
        <p> e.g. <a href="api/coverage/A0A016S8J7">http://127.0.0.1:8000/api/coverage/A0A016S8J7   </a> </p>

        <h3> Add Protein: </h3>
        <p> <b> <em> POST http://127.0.0.1:8000/api/protein/  </b> </em>-   add a new record</p>
        <p> e.g. <a href="/proteins"> http://127.0.0.1:8000/proteins/    </a> </p>
    </div>
{% endblock %}
<!-- end of code I wrote  -->

midtermBioData/templates/midtermBioData/protein.html
{% extends "./base.html" %}
{% load bootstrap4 %}


{% block content %}
<h1>Proteins</h1>

<!-- This code is personally adapted but structurally inspired by lecture content -->
<table class="table-key">       
    <tr><th>Protein ID: {{ first_protein.protein_id }}</th></tr>         
    <tr><td>Sequence: </td><td>{{ sequence.sequence }}</td></tr>
    <tr><td>Length: </td><td>{{ first_protein.length }}</td></tr> 
    <tr><th>Taxonomy: </th></tr>
    <tr><td>Taxa ID: </td><td>{{ first_protein.taxa_id }}</td></tr>         
    <tr><td>Clade: </td><td>{{ first_protein.clade }}</td></tr> 
    <tr><td>Genus: </td><td>{{ organism.genus }}</td></tr> 
    <tr><td>Species: </td><td>{{ organism.species }}</td></tr>
    <tr><td>----------</td><td>-----------------</td></tr> 
                    
    {% if domains %}
    <tr><th >Domains: </th></tr>
    {% for domain in domains %}
        <tr ><td>Pfam ID:</td><td>{{ domain.pfam_id }}</td></tr>
        <tr><td>Description:</td><td>{{ domain.description }}</td></tr>
        <tr><td>Start:</td><td>{{ domain.start }}</td></tr>
        <tr><td>Stop:</td><td>{{ domain.stop }}</td></tr>
        <tr><td>----------</td><td>-----------------</td></tr> 
        {% for pfam_id in pfam_ids %}
            {% if pfam_id.domain_id.pfam_id == domain.pfam_id %}
            <tr><td>Domain: ID</td><td>{{ pfam_id.domain_id }}</td></tr>
            <tr><td>Domain Description:</td><td>{{ pfam_id.domain_description }}</td></tr>
            <tr><td>----------</td><td>-----------------</td></tr> 
            <tr><td>----------</td><td>-----------------</td></tr> 
            {% endif %}
        {% endfor %}
    {% endfor %}
    {% endif %}      
<!-- End of code personally adapted but structurally inspired by lecture content -->      
</table>
{% endblock %}

midtermBioData/templates/midtermBioData/proteins.html
{% extends "./base.html" %}

{% load static %}
{% load bootstrap4 %}

{% block content %}
    <h1>Proteins</h1>
<!-- I wrote this code  -->
    <div class="container">
        <div class="proteins-list">
            <table>
                <tr>
                    <th>Protein ID</th>
                </tr>
                {% for protein in proteins %}
                    <tr>
                        <td><a href="/protein/{{protein.protein_id}}">{{protein.protein_id}}</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
<!--End of code I wrote -->

<!-- I wrote this code but consulted documentation for django forms -->
        <div class="form-container">
            <h2>Add Protein</h2>
            <form method="POST" action="/proteins/">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_protein_id">Protein ID:</label>
                    {{ form.protein_id }}
                </div>
                <div class="form-group">
                    <label for="id_clade">Clade:</label>
                    {{ form.clade }}
                </div>
                <div class="form-group">
                    <label for="id_length">Length:</label>
                    {{ form.length }}
                </div>
                <div class="form-group">
                    <label for="id_pfam_id">Pfam ID:</label>
                    {{ form.pfam_id }}
                </div>
                <div class="form-group">
                    <label for="id_taxa_id">Taxa ID:</label>
                    {{ form.taxa_id }}
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
 <!-- End of I wrote while consulting documentation for django forms -->      

 <!-- I wrote this code but researched online how to embed the message -->      
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
 <!-- End of code I wrote researching online how to embed the message -->      
    </div>
  
{% endblock %}

midtermBioData/templates/midtermBioData/title.html
<!-- This code is written guided by lecture content -->
{% load static %}
{% load bootstrap4 %}
<div id="header"> 
    <img class="img" src="https://plus.unsplash.com/premium_photo-1676226342566-3fb5f2e1f7ae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1032&q=80">
    <h1 id="app-title"> Protein Data</h1>
</div>
<div id="navigation"> 
    <a href="/"> REST API Endpoints</a>
</div>
<!-- End of code written guided by lecture content -->